### ISSUE TITLE
create listing overview page

### ISSUE THREAD

**Issue by Papayaman1000** [Ohesachite/hyland-hackathon-project-1#10]
create a page for displaying information about a listing; should be like a watered-down user profile page and include the following:
- job title
- job description
- skills wanted (at set proficiency levels)
- link to the profile page of the company that created the listing

ideally, this page should be easily displayable in a sidebar on the filter page (as an `iframe` element), which will be allowed roughly 25-33% of the width of the content container, so keep the design fairly simple

as always, I'll handle populating it with data, just get it blocked out to accept said data

**Comment by Ejeffers1239** [comment]
listOver.html is this
