### ISSUE TITLE
Create "ready for Javascript" branch in github

### ISSUE THREAD

**Issue by Ejeffers1239** [Ohesachite/hyland-hackathon-project-1#11]

**Comment by Papayaman1000** [comment]
I'll create that after I finish blocking out the major front-end undertakings that I'm mostly delegating to you guys. Ideally, I'd suggest that each of you create a new branch of your personal repositories to merge such items and accumulate them until I'm ready to undertake them. I'll also create a Project dedicated to holding issues for these.

When updating an issue for a logic-ready page (edit the page/feature's issue via the sidebar on the right), set the Tags to `enhancement` and `priority high`, set the Project to `logic and interactivity`, and set me (Papayaman1000) as the Assignee. You don't strictly _have_ to, but if you do, it lets me spend less time hunting them down and more time actually developing, so _please do!_
