### ISSUE TITLE
"create profile" page -- users

### ISSUE THREAD

**Issue by Papayaman1000** [Ohesachite/hyland-hackathon-project-1#4]
layout: allow user to create a profile and add the following information to it:
- full name
- a basic bio
- upload a profile picture (medium-to-low priority)
- an assortment of skills (tags) and a proficiency rating in them (on a scale of 1 to 7; maybe use a slider?)

**Comment by Ohesachite** [comment]
have part of this down but need to sleep

**Comment by Ejeffers1239** [comment]
manageProfile.html
