### ISSUE TITLE
"create profile" page -- companies

### ISSUE THREAD

**Issue by Papayaman1000** [Ohesachite/hyland-hackathon-project-1#6]
page to create a profile of a company -- should be similar to user profile creation

again, options to add:
- company name
- company bio
- company photo (low-to-medium priority)
- a few traits about the company with ratings on a scale of 1-7 (tags, similar to skills) (medium priority)

and, once again, I'll handle actually storing the data after it's collected and so on

**Comment by Ejeffers1239** [comment]
compProfCreate.html
