### ISSUE TITLE
"create profile" page -- position

### ISSUE THREAD

**Issue by Papayaman1000** [Ohesachite/hyland-hackathon-project-1#7]
a page for a company to create a new job listing
it's going to be like a watered-down version of a user profile creation page
it should allow the job poster to add the following:
- listing/position name
- short description
- requested skills (with proficiency ratings on a scale of one to seven)

as per usual, i'll handle getting the data processed and such, just set up the page to input it

**Comment by Ejeffers1239** [comment]
listCreate.html
