### ISSUE TITLE
create user profile page

### ISSUE THREAD

**Issue by Papayaman1000** [Ohesachite/hyland-hackathon-project-1#8]
this page should serve to display the profile information input by users
should include the following:
- full name
-profile picture (medium priority, but moreso than actually uploading them -- it's much easier to implement. set them as `background-image: url(http://placekitten.com/<horizontal-size>/<vertical-size>);` for now)
- bio
- list of skills they have, but with the peer-reviewed scores (I'll worry about that, just make sure they're not changed for now)

future milestones may include allowing users to edit sections of the page (upload new profile pic, rewrite bio, re-assign skill proficiency values) but that's much further down the line and very low priority

**Comment by Ejeffers1239** [comment]
profileManage.html

**Comment by Ejeffers1239** [comment]
userPage.html
