### ISSUE TITLE
create company overview page

### ISSUE THREAD

**Issue by Papayaman1000** [Ohesachite/hyland-hackathon-project-1#9]
should be similar to user profile page, but more extensive
should include:
- company name
- company picture (like user profile, not urgent but much easier than dealing with uploads)
- company bio/description
- company tags (like skills but focused around workplace environment -- peer-reviewed scores)
- a section to display some of the company's recent listings (perhaps with a link to the position search page that sets it to filter for that company; medium-to-low priority)

as always I'll handle actually populating it with data, just get a layout done for now

**Comment by Ejeffers1239** [comment]
empPage.html
